### ISSUE TITLE
xml.etree.ElementTree.ParseError: undefined entity &nbsp;

### ISSUE THREAD

**Issue by aaronxn** [jbmorley/evernote-bookmarks#3]
Got another one for ya:

```
Traceback (most recent call last):
  File "./evernote-bookmarks", line 124, in <module>
    main()
  File "./evernote-bookmarks", line 120, in main
    convert(options.input, options.output)
  File "./evernote-bookmarks", line 72, in convert
    en_note = ElementTree.fromstring(content.encode('utf-8'))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: undefined entity &nbsp;: line 4, column 964
```

The Evernote files I'm trying to import to Pinboard is 300+ MB each (1,000 bookmarks each file), so I'll not upload unless necessary. Suffice it to say, if the Evernote entry has &nbsp in it, the parsing fails. 

I found one of the offending Evernote entries and did the following:

grep -i -n 

Output: [A6grep.log.zip](https://github.com/jbmorley/evernote-bookmarks/files/324015/A6grep.log.zip)

As you can see, `&nbsp;` is present. I fixed a few of the Evernote Exported files manually, replacing `&nbsp;` with a space. This enabled parsing to complete successfully, unless another html encoded character caused problems. Sadly, I have several thousand more bookmarks to export, so doing this manually is a pain in the neck. 

Suggestions: 

Decode all html entities / escape-characters.

http://stackoverflow.com/questions/628332/decoding-html-entities-with-python
http://stackoverflow.com/questions/11405996/how-can-i-use-python-to-replace-html-escape-characters

My Python is not up to par, so I'll leave the code modifications to you.

**Comment by jbmorley** [comment]
Very happy to look into this, but it's going to take me a couple of weeks to get around to it I'm afraid.

**Comment by ToasterFaerie** [comment]
I am also getting a similar error on some bookmarks. Has there been any progress on this?

My enx file is also large and I'm not sure how to find the offending bookmarks, but am happy to provide any information I can.

I know it's been a while and you may not be interested in this project anymore. In any case, thanks for the tool!

**Comment by jbmorley** [comment]
Would you be able to provide me (privately) with your bookmarks file so I can test it locally?

**Comment by ToasterFaerie** [comment]
No problem, I can send them to you later today when I get home.

Edit: Where can I contact you to give you the file?

**Comment by rijk82** [comment]
In addition to the above parsing errors caused by html encoded characters I've now run into a `not well-formed (invalid token)` error. Whilst I can manually clean the html characters, I'm not sure what to do with this one?

**Comment by QDxiaoye** [comment]
I am also getting a similar error and find out that a Encoding error when open it by safari. Then, I find a '&' is the culprit.

**Comment by pawamoy** [comment]
See https://github.com/pawamoy/mkdocstrings/issues/129 in case anyone is interested in fixing this :wink:

**Comment by hsiktas** [comment]
My workaround was to run `sed -i 's/\&nbsp;/ /g' ./foo.enex` on my Evernote exports, and altogether this script exported over 2000 bookmarks together with their tags preserved. 😊
Please note that BSD sed has a slightly different syntax if you are on macOS: https://unix.stackexchange.com/questions/401905/bsd-sed-vs-gnu-sed-and-i
